replicaCount: 1

image:
  repository: 532549085896.dkr.ecr.ap-south-1.amazonaws.com/incident-responder
  tag: 223528f21564e90b45dd957a9556eb4417ebea26
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 5

imagePullSecrets:
  - name: ecr-pull-secret

secretName: incident-responder-secrets
slackChannelId: C0B4XPXBNKU
